@host = 127.0.0.1:8787
@version = v1
@latest = 90
@auth_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraWxscG9wMzc3MCIsImV4cCI6MTcyMTA3MjQ3NX0.L1CtPgHlQ9k-Sluh_KyW7ObibVp4cm85mc0f8HbZ0yA

###
POST http://{{host}}/{{version}}/login
Content-Type: application/json

{
  "login": "killpop3770",
  "password": "zhopka123"
}

###
GET http://{{host}}/{{latest}}/login_info
Authorization: Bearer {{auth_token}}


GET http://{{host}}/
Accept: application/json

###

GET http://{{host}}/{{version}}/tasks123
Accept: application/json

###

GET http://{{host}}/{{version}}/tasks
Accept: application/json

###

POST http://{{host}}/{{version}}/tasks
Content-Type: application/json

{
  "name": "do some work",
  "priority": 1
}

###

PATCH http://{{host}}/{{version}}/tasks/{{latest}}
Content-Type: application/json

{
  "name": "chill?",
  "priority": 100
}

###

PATCH http://{{host}}/{{version}}/tasks/{{latest}}
Content-Type: application/json

{
  "name": "sleep"
}

###

PATCH http://{{host}}/{{version}}/tasks/{{latest}}
Content-Type: application/json

{
  "priority": 42
}

###

DELETE http://{{host}}/{{version}}/tasks/{{latest}}
Content-Type: application/json

###
