@host = 127.0.0.1:8787
@version = v1
@latest = 8

GET http://{{host}}/
Accept: application/json

###

GET http://{{host}}/{{version}}/tasks123
Accept: application/json

###

GET http://{{host}}/{{version}}/tasks
Accept: application/json

###

POST http://{{host}}/{{version}}/tasks
Content-Type: application/json

{
  "name": "do some work",
  "priority": 1
}

###

PATCH http://{{host}}/{{version}}/tasks/{{latest}}
Content-Type: application/json

{
  "name": "chill?",
  "priority": 100
}

###

PATCH http://{{host}}/{{version}}/tasks/{{latest}}
Content-Type: application/json

{
  "name": "sleep"
}

###

PATCH http://{{host}}/{{version}}/tasks/{{latest}}
Content-Type: application/json

{
  "priority": 42
}

###

DELETE http://{{host}}/{{version}}/tasks/{{latest}}
Content-Type: application/json

###
